/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkstationsRouteImport } from './routes/workstations'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QcRouteImport } from './routes/qc'
import { Route as MesRouteImport } from './routes/mes'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ExecutionRouteImport } from './routes/execution'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkOrdersIndexRouteImport } from './routes/work-orders.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductionOrdersIndexRouteImport } from './routes/production-orders.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as WorkOrdersWoIdRouteImport } from './routes/work-orders.$woId'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ProductionOrdersPoIdRouteImport } from './routes/production-orders.$poId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as ApiPublicWebhooksQcRouteImport } from './routes/api/public/webhooks.qc'
import { Route as ApiPublicWebhooksMesRouteImport } from './routes/api/public/webhooks.mes'
import { Route as ApiPublicWebhooksCommandCenterRouteImport } from './routes/api/public/webhooks.command-center'
import { Route as ApiPublicOmsWorkOrdersRouteImport } from './routes/api/public/oms.work-orders'
import { Route as ApiPublicOmsOrdersRouteImport } from './routes/api/public/oms.orders'

const WorkstationsRoute = WorkstationsRouteImport.update({
  id: '/workstations',
  path: '/workstations',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const MesRoute = MesRouteImport.update({
  id: '/mes',
  path: '/mes',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionRoute = ExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersIndexRoute = WorkOrdersIndexRouteImport.update({
  id: '/work-orders/',
  path: '/work-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionOrdersIndexRoute = ProductionOrdersIndexRouteImport.update({
  id: '/production-orders/',
  path: '/production-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersWoIdRoute = WorkOrdersWoIdRouteImport.update({
  id: '/work-orders/$woId',
  path: '/work-orders/$woId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionOrdersPoIdRoute = ProductionOrdersPoIdRouteImport.update({
  id: '/production-orders/$poId',
  path: '/production-orders/$poId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksQcRoute = ApiPublicWebhooksQcRouteImport.update({
  id: '/api/public/webhooks/qc',
  path: '/api/public/webhooks/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMesRoute = ApiPublicWebhooksMesRouteImport.update({
  id: '/api/public/webhooks/mes',
  path: '/api/public/webhooks/mes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksCommandCenterRoute =
  ApiPublicWebhooksCommandCenterRouteImport.update({
    id: '/api/public/webhooks/command-center',
    path: '/api/public/webhooks/command-center',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOmsWorkOrdersRoute = ApiPublicOmsWorkOrdersRouteImport.update({
  id: '/api/public/oms/work-orders',
  path: '/api/public/oms/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOmsOrdersRoute = ApiPublicOmsOrdersRouteImport.update({
  id: '/api/public/oms/orders',
  path: '/api/public/oms/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof CommandCenterRoute
  '/execution': typeof ExecutionRoute
  '/inventory': typeof InventoryRoute
  '/mes': typeof MesRoute
  '/qc': typeof QcRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/users': typeof UsersRoute
  '/workstations': typeof WorkstationsRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/production-orders/$poId': typeof ProductionOrdersPoIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/work-orders/$woId': typeof WorkOrdersWoIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/production-orders/': typeof ProductionOrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/work-orders/': typeof WorkOrdersIndexRoute
  '/api/public/oms/orders': typeof ApiPublicOmsOrdersRoute
  '/api/public/oms/work-orders': typeof ApiPublicOmsWorkOrdersRoute
  '/api/public/webhooks/command-center': typeof ApiPublicWebhooksCommandCenterRoute
  '/api/public/webhooks/mes': typeof ApiPublicWebhooksMesRoute
  '/api/public/webhooks/qc': typeof ApiPublicWebhooksQcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof CommandCenterRoute
  '/execution': typeof ExecutionRoute
  '/inventory': typeof InventoryRoute
  '/mes': typeof MesRoute
  '/qc': typeof QcRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/users': typeof UsersRoute
  '/workstations': typeof WorkstationsRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/production-orders/$poId': typeof ProductionOrdersPoIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/work-orders/$woId': typeof WorkOrdersWoIdRoute
  '/customers': typeof CustomersIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/production-orders': typeof ProductionOrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/work-orders': typeof WorkOrdersIndexRoute
  '/api/public/oms/orders': typeof ApiPublicOmsOrdersRoute
  '/api/public/oms/work-orders': typeof ApiPublicOmsWorkOrdersRoute
  '/api/public/webhooks/command-center': typeof ApiPublicWebhooksCommandCenterRoute
  '/api/public/webhooks/mes': typeof ApiPublicWebhooksMesRoute
  '/api/public/webhooks/qc': typeof ApiPublicWebhooksQcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof CommandCenterRoute
  '/execution': typeof ExecutionRoute
  '/inventory': typeof InventoryRoute
  '/mes': typeof MesRoute
  '/qc': typeof QcRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/users': typeof UsersRoute
  '/workstations': typeof WorkstationsRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/production-orders/$poId': typeof ProductionOrdersPoIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/work-orders/$woId': typeof WorkOrdersWoIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/production-orders/': typeof ProductionOrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/work-orders/': typeof WorkOrdersIndexRoute
  '/api/public/oms/orders': typeof ApiPublicOmsOrdersRoute
  '/api/public/oms/work-orders': typeof ApiPublicOmsWorkOrdersRoute
  '/api/public/webhooks/command-center': typeof ApiPublicWebhooksCommandCenterRoute
  '/api/public/webhooks/mes': typeof ApiPublicWebhooksMesRoute
  '/api/public/webhooks/qc': typeof ApiPublicWebhooksQcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auth'
    | '/command-center'
    | '/execution'
    | '/inventory'
    | '/mes'
    | '/qc'
    | '/settings'
    | '/shipments'
    | '/users'
    | '/workstations'
    | '/customers/$customerId'
    | '/orders/$orderId'
    | '/production-orders/$poId'
    | '/products/$productId'
    | '/work-orders/$woId'
    | '/customers/'
    | '/orders/'
    | '/production-orders/'
    | '/products/'
    | '/work-orders/'
    | '/api/public/oms/orders'
    | '/api/public/oms/work-orders'
    | '/api/public/webhooks/command-center'
    | '/api/public/webhooks/mes'
    | '/api/public/webhooks/qc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auth'
    | '/command-center'
    | '/execution'
    | '/inventory'
    | '/mes'
    | '/qc'
    | '/settings'
    | '/shipments'
    | '/users'
    | '/workstations'
    | '/customers/$customerId'
    | '/orders/$orderId'
    | '/production-orders/$poId'
    | '/products/$productId'
    | '/work-orders/$woId'
    | '/customers'
    | '/orders'
    | '/production-orders'
    | '/products'
    | '/work-orders'
    | '/api/public/oms/orders'
    | '/api/public/oms/work-orders'
    | '/api/public/webhooks/command-center'
    | '/api/public/webhooks/mes'
    | '/api/public/webhooks/qc'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/auth'
    | '/command-center'
    | '/execution'
    | '/inventory'
    | '/mes'
    | '/qc'
    | '/settings'
    | '/shipments'
    | '/users'
    | '/workstations'
    | '/customers/$customerId'
    | '/orders/$orderId'
    | '/production-orders/$poId'
    | '/products/$productId'
    | '/work-orders/$woId'
    | '/customers/'
    | '/orders/'
    | '/production-orders/'
    | '/products/'
    | '/work-orders/'
    | '/api/public/oms/orders'
    | '/api/public/oms/work-orders'
    | '/api/public/webhooks/command-center'
    | '/api/public/webhooks/mes'
    | '/api/public/webhooks/qc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  CommandCenterRoute: typeof CommandCenterRoute
  ExecutionRoute: typeof ExecutionRoute
  InventoryRoute: typeof InventoryRoute
  MesRoute: typeof MesRoute
  QcRoute: typeof QcRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  UsersRoute: typeof UsersRoute
  WorkstationsRoute: typeof WorkstationsRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ProductionOrdersPoIdRoute: typeof ProductionOrdersPoIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  WorkOrdersWoIdRoute: typeof WorkOrdersWoIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductionOrdersIndexRoute: typeof ProductionOrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  WorkOrdersIndexRoute: typeof WorkOrdersIndexRoute
  ApiPublicOmsOrdersRoute: typeof ApiPublicOmsOrdersRoute
  ApiPublicOmsWorkOrdersRoute: typeof ApiPublicOmsWorkOrdersRoute
  ApiPublicWebhooksCommandCenterRoute: typeof ApiPublicWebhooksCommandCenterRoute
  ApiPublicWebhooksMesRoute: typeof ApiPublicWebhooksMesRoute
  ApiPublicWebhooksQcRoute: typeof ApiPublicWebhooksQcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workstations': {
      id: '/workstations'
      path: '/workstations'
      fullPath: '/workstations'
      preLoaderRoute: typeof WorkstationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes': {
      id: '/mes'
      path: '/mes'
      fullPath: '/mes'
      preLoaderRoute: typeof MesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution': {
      id: '/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof ExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/': {
      id: '/work-orders/'
      path: '/work-orders'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof WorkOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-orders/': {
      id: '/production-orders/'
      path: '/production-orders'
      fullPath: '/production-orders/'
      preLoaderRoute: typeof ProductionOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/$woId': {
      id: '/work-orders/$woId'
      path: '/work-orders/$woId'
      fullPath: '/work-orders/$woId'
      preLoaderRoute: typeof WorkOrdersWoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-orders/$poId': {
      id: '/production-orders/$poId'
      path: '/production-orders/$poId'
      fullPath: '/production-orders/$poId'
      preLoaderRoute: typeof ProductionOrdersPoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/qc': {
      id: '/api/public/webhooks/qc'
      path: '/api/public/webhooks/qc'
      fullPath: '/api/public/webhooks/qc'
      preLoaderRoute: typeof ApiPublicWebhooksQcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mes': {
      id: '/api/public/webhooks/mes'
      path: '/api/public/webhooks/mes'
      fullPath: '/api/public/webhooks/mes'
      preLoaderRoute: typeof ApiPublicWebhooksMesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/command-center': {
      id: '/api/public/webhooks/command-center'
      path: '/api/public/webhooks/command-center'
      fullPath: '/api/public/webhooks/command-center'
      preLoaderRoute: typeof ApiPublicWebhooksCommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oms/work-orders': {
      id: '/api/public/oms/work-orders'
      path: '/api/public/oms/work-orders'
      fullPath: '/api/public/oms/work-orders'
      preLoaderRoute: typeof ApiPublicOmsWorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oms/orders': {
      id: '/api/public/oms/orders'
      path: '/api/public/oms/orders'
      fullPath: '/api/public/oms/orders'
      preLoaderRoute: typeof ApiPublicOmsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  CommandCenterRoute: CommandCenterRoute,
  ExecutionRoute: ExecutionRoute,
  InventoryRoute: InventoryRoute,
  MesRoute: MesRoute,
  QcRoute: QcRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
  UsersRoute: UsersRoute,
  WorkstationsRoute: WorkstationsRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductionOrdersPoIdRoute: ProductionOrdersPoIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  WorkOrdersWoIdRoute: WorkOrdersWoIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductionOrdersIndexRoute: ProductionOrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  WorkOrdersIndexRoute: WorkOrdersIndexRoute,
  ApiPublicOmsOrdersRoute: ApiPublicOmsOrdersRoute,
  ApiPublicOmsWorkOrdersRoute: ApiPublicOmsWorkOrdersRoute,
  ApiPublicWebhooksCommandCenterRoute: ApiPublicWebhooksCommandCenterRoute,
  ApiPublicWebhooksMesRoute: ApiPublicWebhooksMesRoute,
  ApiPublicWebhooksQcRoute: ApiPublicWebhooksQcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
