/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReturnsIndexRouteImport } from './routes/returns.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductionOrdersIndexRouteImport } from './routes/production-orders.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as BatchesIndexRouteImport } from './routes/batches.index'
import { Route as ReturnsReturnIdRouteImport } from './routes/returns.$returnId'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ProductionOrdersPoIdRouteImport } from './routes/production-orders.$poId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'
import { Route as ApiPublicWebhooksQcRouteImport } from './routes/api/public/webhooks.qc'
import { Route as ApiPublicWebhooksMesRouteImport } from './routes/api/public/webhooks.mes'
import { Route as ApiPublicOmsWorkOrdersRouteImport } from './routes/api/public/oms.work-orders'
import { Route as ApiPublicOmsOrdersRouteImport } from './routes/api/public/oms.orders'

const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIndexRoute = ReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionOrdersIndexRoute = ProductionOrdersIndexRouteImport.update({
  id: '/production-orders/',
  path: '/production-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsReturnIdRoute = ReturnsReturnIdRouteImport.update({
  id: '/returns/$returnId',
  path: '/returns/$returnId',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RequestsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionOrdersPoIdRoute = ProductionOrdersPoIdRouteImport.update({
  id: '/production-orders/$poId',
  path: '/production-orders/$poId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksQcRoute = ApiPublicWebhooksQcRouteImport.update({
  id: '/api/public/webhooks/qc',
  path: '/api/public/webhooks/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMesRoute = ApiPublicWebhooksMesRouteImport.update({
  id: '/api/public/webhooks/mes',
  path: '/api/public/webhooks/mes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOmsWorkOrdersRoute = ApiPublicOmsWorkOrdersRouteImport.update({
  id: '/api/public/oms/work-orders',
  path: '/api/public/oms/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOmsOrdersRoute = ApiPublicOmsOrdersRouteImport.update({
  id: '/api/public/oms/orders',
  path: '/api/public/oms/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/requests': typeof RequestsRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/production-orders/$poId': typeof ProductionOrdersPoIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/returns/$returnId': typeof ReturnsReturnIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/production-orders/': typeof ProductionOrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/api/public/oms/orders': typeof ApiPublicOmsOrdersRoute
  '/api/public/oms/work-orders': typeof ApiPublicOmsWorkOrdersRoute
  '/api/public/webhooks/mes': typeof ApiPublicWebhooksMesRoute
  '/api/public/webhooks/qc': typeof ApiPublicWebhooksQcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/requests': typeof RequestsRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/production-orders/$poId': typeof ProductionOrdersPoIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/returns/$returnId': typeof ReturnsReturnIdRoute
  '/batches': typeof BatchesIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/production-orders': typeof ProductionOrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/returns': typeof ReturnsIndexRoute
  '/api/public/oms/orders': typeof ApiPublicOmsOrdersRoute
  '/api/public/oms/work-orders': typeof ApiPublicOmsWorkOrdersRoute
  '/api/public/webhooks/mes': typeof ApiPublicWebhooksMesRoute
  '/api/public/webhooks/qc': typeof ApiPublicWebhooksQcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/requests': typeof RequestsRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/production-orders/$poId': typeof ProductionOrdersPoIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/returns/$returnId': typeof ReturnsReturnIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/production-orders/': typeof ProductionOrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/api/public/oms/orders': typeof ApiPublicOmsOrdersRoute
  '/api/public/oms/work-orders': typeof ApiPublicOmsWorkOrdersRoute
  '/api/public/webhooks/mes': typeof ApiPublicWebhooksMesRoute
  '/api/public/webhooks/qc': typeof ApiPublicWebhooksQcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auth'
    | '/requests'
    | '/set-password'
    | '/settings'
    | '/shipments'
    | '/batches/$batchId'
    | '/customers/$customerId'
    | '/orders/$orderId'
    | '/production-orders/$poId'
    | '/products/$productId'
    | '/requests/$id'
    | '/returns/$returnId'
    | '/batches/'
    | '/customers/'
    | '/orders/'
    | '/production-orders/'
    | '/products/'
    | '/returns/'
    | '/api/public/oms/orders'
    | '/api/public/oms/work-orders'
    | '/api/public/webhooks/mes'
    | '/api/public/webhooks/qc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auth'
    | '/requests'
    | '/set-password'
    | '/settings'
    | '/shipments'
    | '/batches/$batchId'
    | '/customers/$customerId'
    | '/orders/$orderId'
    | '/production-orders/$poId'
    | '/products/$productId'
    | '/requests/$id'
    | '/returns/$returnId'
    | '/batches'
    | '/customers'
    | '/orders'
    | '/production-orders'
    | '/products'
    | '/returns'
    | '/api/public/oms/orders'
    | '/api/public/oms/work-orders'
    | '/api/public/webhooks/mes'
    | '/api/public/webhooks/qc'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/auth'
    | '/requests'
    | '/set-password'
    | '/settings'
    | '/shipments'
    | '/batches/$batchId'
    | '/customers/$customerId'
    | '/orders/$orderId'
    | '/production-orders/$poId'
    | '/products/$productId'
    | '/requests/$id'
    | '/returns/$returnId'
    | '/batches/'
    | '/customers/'
    | '/orders/'
    | '/production-orders/'
    | '/products/'
    | '/returns/'
    | '/api/public/oms/orders'
    | '/api/public/oms/work-orders'
    | '/api/public/webhooks/mes'
    | '/api/public/webhooks/qc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  RequestsRoute: typeof RequestsRouteWithChildren
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  BatchesBatchIdRoute: typeof BatchesBatchIdRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ProductionOrdersPoIdRoute: typeof ProductionOrdersPoIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ReturnsReturnIdRoute: typeof ReturnsReturnIdRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductionOrdersIndexRoute: typeof ProductionOrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ReturnsIndexRoute: typeof ReturnsIndexRoute
  ApiPublicOmsOrdersRoute: typeof ApiPublicOmsOrdersRoute
  ApiPublicOmsWorkOrdersRoute: typeof ApiPublicOmsWorkOrdersRoute
  ApiPublicWebhooksMesRoute: typeof ApiPublicWebhooksMesRoute
  ApiPublicWebhooksQcRoute: typeof ApiPublicWebhooksQcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/': {
      id: '/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof ReturnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-orders/': {
      id: '/production-orders/'
      path: '/production-orders'
      fullPath: '/production-orders/'
      preLoaderRoute: typeof ProductionOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/': {
      id: '/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/$returnId': {
      id: '/returns/$returnId'
      path: '/returns/$returnId'
      fullPath: '/returns/$returnId'
      preLoaderRoute: typeof ReturnsReturnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-orders/$poId': {
      id: '/production-orders/$poId'
      path: '/production-orders/$poId'
      fullPath: '/production-orders/$poId'
      preLoaderRoute: typeof ProductionOrdersPoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/qc': {
      id: '/api/public/webhooks/qc'
      path: '/api/public/webhooks/qc'
      fullPath: '/api/public/webhooks/qc'
      preLoaderRoute: typeof ApiPublicWebhooksQcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mes': {
      id: '/api/public/webhooks/mes'
      path: '/api/public/webhooks/mes'
      fullPath: '/api/public/webhooks/mes'
      preLoaderRoute: typeof ApiPublicWebhooksMesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oms/work-orders': {
      id: '/api/public/oms/work-orders'
      path: '/api/public/oms/work-orders'
      fullPath: '/api/public/oms/work-orders'
      preLoaderRoute: typeof ApiPublicOmsWorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oms/orders': {
      id: '/api/public/oms/orders'
      path: '/api/public/oms/orders'
      fullPath: '/api/public/oms/orders'
      preLoaderRoute: typeof ApiPublicOmsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RequestsRouteChildren {
  RequestsIdRoute: typeof RequestsIdRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsIdRoute: RequestsIdRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  RequestsRoute: RequestsRouteWithChildren,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
  BatchesBatchIdRoute: BatchesBatchIdRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductionOrdersPoIdRoute: ProductionOrdersPoIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ReturnsReturnIdRoute: ReturnsReturnIdRoute,
  BatchesIndexRoute: BatchesIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductionOrdersIndexRoute: ProductionOrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ReturnsIndexRoute: ReturnsIndexRoute,
  ApiPublicOmsOrdersRoute: ApiPublicOmsOrdersRoute,
  ApiPublicOmsWorkOrdersRoute: ApiPublicOmsWorkOrdersRoute,
  ApiPublicWebhooksMesRoute: ApiPublicWebhooksMesRoute,
  ApiPublicWebhooksQcRoute: ApiPublicWebhooksQcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
